# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and Upload TestFlight"
  lane :appstore do
    api_key = app_store_connect_api_key(
      key_id: "DMSP28L983",
      issuer_id: "4e287f85-c492-4715-9c45-8f8ec50b6e52",
      key_content: ENV['ASC_KEY_CONTENT'],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    username = ENV["USERNAME"]
    personal_github_access_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]
    authorization_token_str = "#{username}:#{personal_github_access_token}"
    basic_authorization_token = Base64.strict_encode64(authorization_token_str)

    # setup certificates for signing
    match(
      git_basic_authorization: basic_authorization_token,
      api_key: api_key,
      app_identifier: 'com.holly.reactnativebootstrap',
      type: "appstore",
      readonly: is_ci
    )

    # increment version
    increment_build_number()

    # build app
    gym(
      clean: true,
      scheme: "ReactNativeFirebaseBootstrapApp",
      configuration: "Release",
      output_name: "app.ipa"
    )

    # distribute to testflight
    pilot(
      api_key: api_key,
      ipa: "./app.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
