# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and Upload TestFlight"
  lane :appstore do
    api_key = app_store_connect_api_key(
      key_id: "DMSP28L983",
      issuer_id: "4e287f85-c492-4715-9c45-8f8ec50b6e52",
      key_filepath: File.join(Dir.pwd, "keys/appstore_key.p8"),
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    match(type: "appstore", readonly: is_ci)
    gym(
      clean: true,
      scheme: "ReactNativeFirebaseBootstrapApp",
      configuration: "Release",
      output_name: "app.ipa"
    )
    pilot(
      ipa: "./app.ipa"
    )
  end
end
