name: deploy-ios-appstore

on:
  push:
    tags:
      - 'v*'

env:
  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.18.1"
          cache: "yarn"

      - run: npm install -g yarn
      - run: yarn install --immutable

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Bundle install
        run: bundle install
        working-directory: projects/app/ios

      - uses: actions/cache@v2
        with:
          path: projects/app/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pod Install
        if: steps.cache-cocoapods.outputs.cache-hit != 'true'
        run: pod install
        working-directory: projects/app/ios

      - name: Post to Slack on start
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          attachments: |
            [
              {
                "color": "warning",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "${{ github.workflow }}",
                "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "appのAppStoreへのデプロイを開始します！",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}"
                  },
                  {
                    "title": "Commit URL",
                    "value": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                  }
                ]
              }
            ]

      - name: Upload a new build to App Store Connect
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          PERSONAL_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
        run: bundle exec fastlane appstore
        working-directory: projects/app/ios

      - name: Post to Slack on success
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "${{ github.workflow }}",
                "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "appのAppStoreへのデプロイが成功しました！",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}"
                  },
                  {
                    "title": "Commit URL",
                    "value": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                  }
                ]
              }
            ]

      - name: Post to Slack on failure
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          attachments: |
            [
              {
                "color": "danger",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "${{ github.workflow }}",
                "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "appのAppStoreへのデプロイが失敗しました",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}"
                  },
                  {
                    "title": "Commit URL",
                    "value": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                  }
                ]
              }
            ]
