name: deploy-ios-appdistribution

on:
  push:
    branches:
      - main

env:
  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.18.1"
          cache: "yarn"

      - run: npm install -g yarn

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - run: yarn install --immutable

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Bundle install
        run: bundle install
        working-directory: projects/app/android

      - name: Post to Slack on start
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          attachments: |
            [
              {
                "color": "warning",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "${{ github.workflow }}",
                "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "androidのFirebaseAppDistributionへのデプロイを開始します！",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}"
                  },
                  {
                    "title": "Commit URL",
                    "value": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                  }
                ]
              }
            ]

      - name: Restore keystore file
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > projects/app/android/app/release.keystore

      - name: Upload a new build to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: bundle exec fastlane appdistribution
        working-directory: projects/app/android

      - name: Post to Slack on success
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "${{ github.workflow }}",
                "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "androidのFirebaseAppDistributionへのデプロイが成功しました！",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}"
                  },
                  {
                    "title": "Commit URL",
                    "value": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                  }
                ]
              }
            ]

      - name: Post to Slack on failure
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@main
        with:
          attachments: |
            [
              {
                "color": "danger",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "${{ github.workflow }}",
                "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "androidのFirebaseAppDistributionへのデプロイが失敗しました",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}"
                  },
                  {
                    "title": "Commit URL",
                    "value": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                  }
                ]
              }
            ]
